export const LIKE_EVENT_REQUEST = 'LIKE_EVENT_REQUEST';
export const LIKE_EVENT_SUCCESS = 'LIKE_EVENT_SUCCESS';
export const LIKE_EVENT_FAILURE = 'LIKE_EVENT_FAILURE';

export const UNLIKE_EVENT_REQUEST = 'UNLIKE_EVENT_REQUEST';
export const UNLIKE_EVENT_SUCCESS = 'UNLIKE_EVENT_SUCCESS';
export const UNLIKE_EVENT_FAILURE = 'UNLIKE_EVENT_FAILURE';
