export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST"
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS"
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE"

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE"

export const GET_FOLLOWERS_REQUEST = "GET_FOLLOWERS_REQUEST"
export const GET_FOLLOWERS_SUCCESS = "GET_FOLLOWERS_SUCCESS"
export const GET_FOLLOWERS_FAILURE = "GET_FOLLOWERS_FAILURE"
